# Stage 1: Build
FROM node:20-alpine AS builder
WORKDIR /app
COPY ./client/package.json ./package.json
COPY ./client/package-lock.json ./package-lock.json
RUN npm ci
COPY ./client/. .
RUN npm run build

# Stage 2: Serve static files with Node.js (using 'serve')
FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY ./client/startup.sh.node /startup.sh
RUN npm install -g serve && chmod +x /startup.sh
EXPOSE 80
CMD ["/startup.sh"]
